# 转向系统参数
#roadsenseparam:
Ks: 0.31
Bs: 0.07
Is: 0.023
d: 0.1
lambda: 10.93
theta: 2.3
r0: 0
ksi: 0.035
R: 0.035
epsilon: 0.74
miu: 0.7

# 车辆参数
#vehicleparam:
mb: 1270
mw: 35
hg: 0.54
Bf: 1.675
L: 2.9
Lr: 1.895
Lf: 1.005

# CAN参数
canport: can0